services:
  - type: web
    name: gidroatlas
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd frontend && npm ci --include=dev && npm run build && cd ../backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: RAPIDAPI_KEY
        sync: false

